server:
  port: 8080

spring:
  datasource:
    username: seric
    password: xsn@1314
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://nnyy.fun:3306/nnyy?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    hikari:
      connection-timeout: 6000
      validation-timeout: 6000
      idle-timeout: 6000
      login-timeout: 6000
      max-lifetime: 6000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false

    druid:
      #     配置初始化大小、最小、最大线程数
      initialSize: 5
      minIdle: 5
      #     CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
      maxActive: 10
      #     最大等待时间，内网：800，外网：1200（三次握手1s）
      maxWait: 10000
      timeBetweenEvictionRunsMillis: 10000
      #     配置一个连接在池中最大空间时间，单位是毫秒
      minEvictableIdleTimeMillis: 60000
      validationQuery: SELECT 1
      testWhileIdle: true
      #     设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnBorrow: true
      #     设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: true
      #     可以支持PSCache（提升写入、查询效率）
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      #     保持长连接
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    stime-zone: GMT+8


mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名，也可实体类字段上加上@TableLogic注解
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值


#logging:
#  config: classpath:log4j2/log4j2-spring.xml
#  level:
#    com.baomidou.mybatisplus.samples.quickstart: debug